server {
    listen 80;
    server_name spingu.smkn1pulaurakyat.sch.id;

    root /home/catur/catur-arena/client/dist;
    index index.html;

    location / {
        try_files \ \/ /index.html;
    }

    location /api {
        proxy_pass http://localhost:4000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \System.Management.Automation.Internal.Host.InternalHost;
        proxy_cache_bypass \;
    }

    location /socket.io {
        proxy_pass http://localhost:4000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \System.Management.Automation.Internal.Host.InternalHost;
    }
}
